### ISSUE TITLE
4 finger gesture kind of buggy

### ISSUE THREAD

**Issue by EddoWagt** [icedman/gnome-shell-hammer#2]
Hey, I just installed this tweak through the script and it works, but it is kind of buggy.
The animation hangs when I release it too early and all open windows simply stop reacting to any input after the gesture... Do you have a way to undo the script? 
I installed the extension after, but that completely breaks the gesture now if enabled (I guess because it conflicts with the script)

**Comment by icedman** [comment]
Simply reinstall the gnome-shell and  use the extension version.

Copy the contents under gnome-extension to ~/.local/share/gnome-shell/extensions/org.gnome.shell.extensions.gnome-shell-hammer

Then enable the extension. The script hasn't been tested with the latest gnome shell versions.

**Comment by EddoWagt** [comment]
Thanks, I guess the script is a bit broken then, It's working now!
